### ISSUE TITLE
mupen64plus fails to start on Ubuntu 17.04 because cannot find libpng12

### ISSUE THREAD

**Issue by Xenphor** [m64p/m64p.github.io#1]
I am not able to use the latest binary release of m64p because mupen64plus can't find libpng12. This library is not in 17.04 so I can't install it. I was able to get it working in arch linux because arch has libpng12. 

UI-Console Error: dlopen('./libmupen64plus.so.2') failed: libpng12.so.0: cannot open shared object file: No such file or directory
UI-Console Error: AttachCoreLib() Error: failed to find Mupen64Plus Core library

**Comment by loganmc10** [comment]
Thanks for reporting this. It also requires freetype2, and on Ubuntu 16.04 freetype2 depends on libpng12. I change the buildbot to build using Debian Stretch. There, freetype2 depends on libpng16.

Anyway, can you try the latest build:
http://m64p.s3-website-us-east-1.amazonaws.com/201707/

**Comment by Xenphor** [comment]
Thanks that works.
