### ISSUE TITLE
Unable to Download

### ISSUE THREAD

**Issue by OptimalJew** [m64p/m64p.github.io#2]
The download link: http://m64p.s3-website-us-east-1.amazonaws.com/ leads to a blank page with "Error: [object Object]".

Using Firefox 55.0.3 on Win7.

**Comment by loganmc10** [comment]
Do you use the "https everywhere" extension?

**Comment by OptimalJew** [comment]
I do indeed. Disabled it and what do you know, it worked.

Much appreciated.

**Comment by loganmc10** [comment]
Yeah it's because the download is hosted on amazonaws.com, and thatextension thinks it should be using HTTPS, but I don't have it setup for HTTPS. I still need to figure out a different hosting solution

**Comment by loganmc10** [comment]
I'm going to reopen this since so many people have run into this issue. I need to look for a better place host these files

**Comment by loganmc10** [comment]
Ok I've updated the download links, they point to https links now, so this should be solved

**Comment by OptimalJew** [comment]
Can confirm that the new links do work with 'https everywhere' enabled.  Glad to see the solved, and I wanted to thank you for the work you're doing with m64p.

**Comment by loganmc10** [comment]
Thanks I'm glad you're enjoying it
