### ISSUE TITLE
m64p is in violation of the GPL

### ISSUE THREAD

**Issue by jessicamaybe** [m64p/m64p.github.io#4]
Hi, the piece of software that you have behind your patreon (Mupen64Plus + GLideN64) is in violation of the GPL license. The link to the github for the project seems to be invalid. Please include a way to request the source code on the website or provide access to a download on the website/github.

**Comment by loganmc10** [comment]
The source code is here:

https://github.com/m64p/mupen64plus-gui

That is for the GUI, everything else is just pulled from the publicly available GitHub repos
